SecureSECODAO/dao-webapp

src/components/layout/Layout.tsx, src/components/newProposal/StepOneMetadata.tsx, src/components/newProposal/StepThreeActions.tsx, src/components/newProposal/StepTwoVoting.tsx, src/components/newProposal/actions/MintTokensAction.tsx, src/components/newProposal/actions/WithdrawAssetsAction.tsx, src/components/newProposal/stepFourConfirmation.stories.tsx, src/components/newProposal/viewProposal/ViewStepThree.tsx, src/components/newProposal/viewProposal/ViewStepTwo.stories.tsx, src/pages/NewProposal.tsx
@Hidde-Heijnen pages have been made 'more' responsive. That is to say, it is not yet perfect but it is a lot better.
=> New proposal page make responsive

src/components/newProposal/viewProposal/ViewStepOne.tsx, src/components/proposal/ProposalResources.tsx, src/lib/utils.test.ts
Adds resources to the 4th step of the new-proposal-form
=> New proposal page step 4 add resources

src/components/layout/Navbar.tsx, src/env.d.ts, src/main.tsx, src/pages/Verification.tsx
Added a link to the Verification page to the nav bar. Also updated the type of the env variable `VITE_VERIFY_CONTRACT`, to fix a bug caused by the previous pull request, that updated the env declaration file.
=> feat: add verification to nav

src/lib/data-utils.test.ts
I have added tests for date-utils.
Fixes # (issue)
Test writing
Please delete options that are not relevant.
Well, let's just say the tests pass.
=> feat: add tests for date-utils.ts

src/components/newProposal/steps/Confirmation.stories.tsx, src/components/newProposal/steps/Confirmation.tsx, src/components/ui/TextareaWYSIWYG.tsx, src/index.css
HTML UL and OL tags were not displayed properly. This is fixed now.
=> WIP: Fix confirmation lists

src/components/dashboard/MembersList.tsx, src/components/ui/Address.stories.tsx, src/components/ui/Address.tsx, src/components/ui/Card.tsx, src/components/ui/Label.tsx, src/components/ui/Tooltip.stories.tsx
Improve Address component by following changes:
- Add property `jazziconSize`, which (if set) adds a Jazzicon to the left of the address (and used this instead of manually adding Jazzicon in front of address component in `MembersList.tsx`)
- Change colors of the link to block explorer
- Changed icon of copy button
- Added toast and check icon when copy was clicked
- Added tooltips to copy button and block explorer link
Fixes # (issue)
Stories have been updated for Address and Tooltip (to add a story without delay).
=> Improve Address component

src/components/newProposal/actions/MergePRInput.tsx, src/components/newProposal/steps/Actions.stories.tsx, src/components/newProposal/steps/Actions.tsx, src/components/newProposal/steps/Confirmation.tsx, src/components/proposal/ProposalActions.stories.tsx, src/components/proposal/ProposalActions.tsx, src/components/proposal/actions/MergeAction.stories.tsx, src/components/proposal/actions/MergeAction.tsx, src/components/ui/StampCard.stories.tsx, src/pages/Verification.tsx
Added the Github Pull Request Merge action as an available action when creating a proposal.
Storybook and manual visual inspections
=> feat: Add Github PR Merge Action to Proposal

src/index.css
Hotfix for small issue with improved colors
=> fix: add muted-foreground

src/components/newProposal/steps/Metadata.tsx
Refactor/bug fix. Use FieldArray instead of a buggy home-made solution
=> refactor: use react-hook-form FieldArray

src/components/dashboard/MembershipStatus.stories.tsx, src/components/dashboard/MembershipStatus.tsx, src/hooks/useVerification.ts, src/pages/Dashboard.tsx
Banner on dashboard about membership status
No
Not very pretty currently, but this will be fixed in the future.
=> Dashboard join dao card

README.md, src/components/dashboard/MembershipStatus.tsx, src/components/governance/ProposalCard.tsx, src/components/layout/Navbar.tsx, src/components/newProposal/steps/Metadata.tsx, src/components/ui/Accordion.tsx, src/components/ui/Address.tsx, src/components/ui/ConnectWalletWarning.tsx, src/components/ui/Label.tsx, src/components/ui/Tooltip.tsx, src/components/verification/StampCard.tsx, src/index.css, src/pages/Dashboard.tsx
Feature
No
Improved the styling of focused elements where this was not done properly yet
=> Focus styling

src/components/newProposal/actions/MintTokensInput.stories.tsx, src/components/newProposal/actions/WithdrawAssetsInput.stories.tsx, src/components/newProposal/steps/Actions.stories.tsx, src/components/newProposal/steps/Metadata.stories.tsx, src/components/newProposal/steps/Voting.stories.tsx, src/components/ui/TimeZoneSelector.stories.tsx, src/lib/decorators/reactHookFormDecorator.tsx
Added storybook stories for:
Metadata
Voting
TimeZoneSelector
WithdrawAssetsInput
MintTokenInput
=> Add missing storybooks

README.md
Docs update
Added 1 sentence to explain what the project is in the readme.
=> docs: project explanation in readme

src/components/governance/ProposalTag.stories.tsx, src/components/governance/ProposalTag.tsx, src/components/newProposal/actions/ChangeParametersInput.stories.tsx, src/components/newProposal/actions/ChangeParametersInput.tsx, src/components/newProposal/steps/Actions.tsx, src/components/newProposal/steps/Confirmation.tsx, src/components/proposal/actions/ChangeParameterAction.stories.tsx, src/components/proposal/actions/ChangeParameterAction.tsx, src/components/proposal/actions/ProposalActionFilter.tsx, src/components/ui/MainCard.stories.tsx, src/components/ui/MainCard.tsx
Added the skeleton for the change parameter action
=> Feat change param action

package-lock.json, package.json, src/components/ui/Slider.stories.tsx, src/components/ui/Slider.tsx, src/components/ui/TokenAmount/index.tsx, src/lib/constants/tokens.ts, src/pages/ClaimReward.stories.tsx, src/pages/ClaimReward.tsx
Add Claim rewards page.
Still left to do / notes:
- this has not yet been added to the site
- Altough this for now has been put under pages, it could also become a component
- The claim button currently has no behaviour
=> Feat add claim rewards page

package-lock.json, src/components/dashboard/MembershipStatus.stories.tsx, src/components/dashboard/MembershipStatus.tsx, src/pages/Dashboard.tsx
New feature / Refactor
No
Refactored by extracting the Card structure into a separate component.
Added check if the wallet is on the correct network, and a warning card if not.
Slightly improved styling (button, larger text/icon, text changes)
=> Add network check and refactor membership status

src/components/newProposal/actions/WithdrawAssetsInput.tsx, src/components/newProposal/steps/Confirmation.tsx
Extra input for adding custom withdraw address
=> Feat add custom token to withdraw action

src/components/layout/Navbar.tsx, src/main.tsx, src/pages/Mining.stories.tsx, src/pages/Mining.tsx
Added option to add a dropdown to the navbar.
=> Feat add dropdown to navbar

src/components/newProposal/steps/Voting.tsx, src/lib/data-utils.test.ts, src/lib/date-utils.ts
Use custom validation using react hook form setError to create validation for the entire duration field
=> Feat fix min duration new proposal page

src/components/newProposal/steps/Metadata.tsx
Users are forced to add at least one resource.
It is suggested to users to add a place for discussion as resource.
=> feat: enforce at least one resource for new proposal

src/components/dashboard/ClaimDailyReward.stories.tsx, src/components/dashboard/ClaimDailyReward.tsx, src/components/dashboard/MembershipStatus.tsx, src/components/ui/ConditionalButton.tsx, src/hooks/useTimeClaimable.ts, src/pages/Dashboard.tsx
Added a daily reward claim button.
Added the UseTimeClaimable hook.
Added the ClaimDailyReward component and tokens.
Added the component to the dashboard.
Still to do in the future (when there is SDK support):
Viewing the maximum amount of REP one could claim and how much rep is gained per timeframe.
=> Feat add claim daily reward page

src/components/newProposal/actions/WithdrawAssetsInput.tsx, src/components/newProposal/steps/Confirmation.stories.tsx, src/components/newProposal/steps/Confirmation.tsx, src/hooks/useDaoBalance.ts, src/lib/constants/actions.tsx, src/lib/constants/patterns.ts, src/lib/patterns.test.ts, src/lib/utils/index.ts
@ThijnK  The order of inputs is a bit wrong when entering NFT token types. Could you take a look at it?
=> Feat add support for more tokentypes new proposal withdraw assets

src/components/governance/ProposalCard.stories.tsx, src/components/newProposal/actions/WithdrawAssetsInput.tsx, src/components/newProposal/steps/Confirmation.tsx, src/components/proposal/ProposalActions.stories.tsx, src/components/proposal/actions/MergeAction.tsx, src/components/proposal/actions/WithdrawAction.stories.tsx, src/components/proposal/actions/WithdrawAction.tsx, src/components/ui/ErrorWrapper.tsx, src/hooks/useDaoBalance.ts, src/hooks/useProposal.ts, src/lib/constants/actions.tsx, src/lib/utils/token.ts
Adjusts the `parseInput` function to support the new Withdraw action stuff.
Adjusts the `WithdrawAction` view component to handle the changes to the Withdraw action format.
Adds support for multiple method names with the same interface for actions.
=> Finalize withdraw assets action

src/components/newProposal/actions/WithdrawAssetsInput.tsx, src/components/newProposal/steps/Confirmation.tsx
Fixed some issues with support for different tokentypes
=> fix: add support for more tokentypes new proposal withdraw assets

package-lock.json, package.json, src/components/dashboard/ClaimDailyRewardCard.stories.tsx, src/components/dashboard/ClaimDailyRewardCard.tsx, src/components/finance/DepositAssets.tsx, src/components/governance/ProposalCard.tsx, src/components/newProposal/steps/Confirmation.tsx, src/components/proposal/ProposalVotes.tsx, src/components/proposal/VotesContent.tsx, src/components/proposal/actions/ActionWrapper.tsx, src/components/ui/Card.tsx, src/components/ui/HeaderCard.tsx, src/components/ui/SortSelector.tsx, src/components/verification/OneTimeRewardCard.stories.tsx, src/components/verification/OneTimeRewardCard.tsx, src/hooks/useMembers.ts, src/hooks/useProposal.ts, src/hooks/useProposals.ts, src/hooks/useTimeClaimable.ts, src/hooks/useVerification.ts, src/hooks/useVotingPower.ts, src/lib/constants/actions.tsx, src/pages/Dashboard.tsx, src/pages/Governance.tsx, src/pages/NewProposal.tsx, src/pages/Verification.tsx, src/pages/ViewProposal.tsx
=> Various proposal fixes 

src/components/newProposal/actions/ChangeParamInput.tsx, src/components/ui/Button.tsx, src/components/ui/Select.tsx, src/hooks/useDaoVariable.ts, src/hooks/useDaoVariables.ts, src/lib/constants/patterns.ts, src/lib/patterns.test.ts
- Added hook to retrieve all params
- Added hook to retreive all params + their current value
- Added hook for getting values of a single param
- ChangeParamInput now uses the hook to retrieve params, thus integrating the DAO with the frontend
- ChangeParamInput applies correct validation for all used solidity types. For ints this includes upper and lower bounds.
=> Feat integrate change plugin param with sdk

package-lock.json, package.json, src/components/dashboard/ClaimDailyRewardCard.tsx, src/components/ui/DataTable.stories.tsx, src/components/ui/DataTable.tsx, src/hooks/useDaoVariable.ts, src/hooks/useDaoVariables.ts, src/hooks/useTier.ts, src/pages/Settings.tsx
See semantic commits for precise changes.
Added simple implementation for settings page
=> Feat settings page show params

src/components/newProposal/actions/ChangeParamInput.tsx, src/lib/constants/DaoVariablesMetadata.ts, src/lib/utils/index.ts
=> Feat add metadata change params

src/components/dashboard/MembershipStatus.tsx, src/components/proposal/ProposalVotes.tsx, src/components/proposal/VotesContent.tsx, src/components/proposal/actions/MergeAction.tsx, src/components/ui/HeaderCard.tsx
Some minor fixes related to spacing/typos/spelling. See commits.
=> Minor fixes

src/components/ui/DataTable.tsx, src/components/ui/PaginationControls.stories.tsx, src/components/ui/PaginationControls.tsx, src/hooks/useProposals.ts, src/pages/Governance.tsx
Added pagination to governance page
=> Feat proposal pagination

package-lock.json, package.json, src/components/layout/ConnectButton.tsx, src/components/layout/Navbar.tsx, src/components/layout/UserBalances.tsx, src/components/proposal/ProposalVotes.tsx, src/components/ui/DataTable.tsx, src/components/ui/PaginationControls.tsx, src/components/ui/Sheet.tsx, src/components/ui/Tabs.tsx, src/hooks/useProposals.ts, src/lib/constants/patterns.test.ts, src/pages/Dashboard.tsx, src/pages/Finance.tsx, src/pages/Governance.tsx, src/pages/ViewProposal.tsx
Updates to new Diamond SDK version, for the filtered proposal count and some fixes.
Various fixes for small styling stuff and things, and also made it so the nav dialog on mobile will close when you click an item.
=> Various styling/functionality fixes

src/components/icons/Diamond.stories.tsx, src/components/icons/Diamond.tsx, src/components/newProposal/actions/MintTokensInput.tsx, src/components/newProposal/steps/Actions.tsx, src/components/newProposal/steps/Voting.tsx, src/components/proposal/ProposalActions.stories.tsx, src/components/proposal/actions/DiamondCutAction.stories.tsx, src/components/proposal/actions/DiamondCutAction.tsx, src/components/ui/Address.tsx, src/components/ui/MainCard.tsx, src/components/ui/Tooltip.tsx, src/hooks/useProposal.ts, src/hooks/useTotalVotingWeight.ts, src/lib/constants/actions.tsx
Quite self explanatory.
Tested using storybook and useDummyData
=> feat: add diamond cut view

src/components/layout/Navbar.tsx, src/lib/constants/config.ts, src/pages/Dashboard.tsx
Add links to docs and swap page to nav
Changed the NavItemCollection to also take a `categories` prop
=> Add links to docs and swap page to nav

src/components/newProposal/actions/MergePRInput.tsx, src/components/newProposal/steps/Actions.tsx, src/components/proposal/actions/MergeAction.tsx, src/hooks/useProposal.ts, src/lib/constants/actions.tsx, src/lib/constants/config.ts, src/pages/Dashboard.tsx
Enhancement
No. New api url added to config.
We now make sure the latest commit is the same at the moment of merging & moment of creating the proposal. To get this value, we retrieve an encrypted commit hash from the pr-merger server.
=> Add latest commit hash to merge action

src/lib/constants/DaoVariablesMetadata.ts
Enhancement
No
Added descriptions for more dao vars (abc, etc.)
=> Add descriptions for more dao vars

src/hooks/useSearchSECO.ts, src/pages/Query.tsx
Bug fix
No
hash cost is displayed properly
amount of hashes is displayed in toast
specific session expired error message
=> Query page fixes

src/lib/constants/config.ts
Fix
Fixed description of the DAO
=> Fix DAO description typo

src/hooks/useDaoBalance.ts, src/hooks/useFacetFetch.ts, src/hooks/useSearchSECO.ts, src/lib/utils/index.ts, src/pages/Finance.tsx
=> Finance page show pools

src/hooks/useSearchSECO.ts
Bug fix
Fixed a bug where it would always display the dummy data 🗿
=> fix: displaying dummy data on success

src/hooks/useSearchSECO.ts, src/pages/Mining.tsx
=> Fix rewarding function call

package-lock.json, package.json, src/lib/constants/DaoVariablesMetadata.ts
remove unnecessary useState, and missed a 0 somewhere
=> fix query estimation bug

package-lock.json, package.json
No
Upgraded version of the diamond-governance-sdk to the latest (1.0.3)
=> Upgrade sdk version
